UNARYOP ::= "+" | "-"
BINARYOP ::= "+" | "-" | "*" | "/"

VAREXPR ::= ( NUM | STR ) | "(" CALCEXPR ")"

UNARYOPEXPR ::=  [ UNARYOP ] VAREXPR
BINARYOPEXPR ::=  UNARYOPEXPR {BINARYOP UNARYOPEXPR}
CALCEXPR ::= BINARYOPEXPR

# FORMATEXPR ::= "{" BINARYOPEXPR "}"